In [ ]:
# usar k8s e proxmox (talvez) para prever active energy

In [1]:
import pandas as pd

data = pd.read_csv('dataset_all_data.csv')
data.head()

,_time,namespace_x,pod_name_x,container_name_x,node_name,inventory-cluster-id_x,inventory-rack-id,inventory-server-id_x,cpu_usage_core_nanoseconds,cpu_usage_nanocores,...,activePower,apparentPower,cumulatedEnergy,current,currentTHD,partialEnergy,peakFactor,powerFactor,reactivePower,latency_ms
0,2025-09-05 10:38:56,quickpizza,quickpizza-8b95978b5-jgvvs,quickpizza,neuronet-k8s-w2,flux,r4,Neuronet-ClusterTest,148544831000,2172538312,...,91.546,86.553,217130.010313,0.399,9.0,217130.010313,1.625,0.996,-0.687,1575.11
1,2025-09-05 10:39:56,quickpizza,quickpizza-8b95978b5-jgvvs,quickpizza,neuronet-k8s-w2,flux,r4,Neuronet-ClusterTest,269400419000,2252322516,...,67.275,69.589,164662.007821,0.295,11.2,164662.007821,1.578,0.990,-6.305,5841.40
2,2025-09-05 10:40:56,quickpizza,quickpizza-8b95978b5-jgvvs,quickpizza,neuronet-k8s-w2,flux,r4,Neuronet-ClusterTest,404545819000,1758135896,...,70.165,74.710,178185.008463,0.308,11.7,178185.008463,1.653,0.986,-7.613,3862.71
3,2025-09-05 10:41:56,quickpizza,quickpizza-8b95978b5-jgvvs,quickpizza,neuronet-k8s-w2,flux,r4,Neuronet-ClusterTest,460082566000,115903139,...,97.096,88.251,217134.010313,0.423,6.2,217134.010313,1.590,0.997,-0.524,805.94
4,2025-09-05 10:42:56,quickpizza,quickpizza-8b95978b5-jgvvs,quickpizza,neuronet-k8s-w2,flux,r4,Neuronet-ClusterTest,499557049000,1424465270,...,59.463,53.114,129720.006161,0.263,12.5,129720.006161,1.678,0.975,-7.156,3250.91

In [3]:
# get numerical columns
numerical_cols = data.select_dtypes(include=['float64', 'int64']).columns
numerical_data = data[numerical_cols]
numerical_data.head()

,cpu_usage_core_nanoseconds,cpu_usage_nanocores,logsfs_available_bytes,logsfs_capacity_bytes,logsfs_used_bytes,memory_major_page_faults,memory_page_faults,memory_rss_bytes,memory_usage_bytes,memory_working_set_bytes,...,activePower,apparentPower,cumulatedEnergy,current,currentTHD,partialEnergy,peakFactor,powerFactor,reactivePower,latency_ms
0,148544831000,2172538312,22659010560,33104523264,32727040,0,285565,78041088,82669568,82669568,...,91.546,86.553,217130.010313,0.399,9.0,217130.010313,1.625,0.996,-0.687,1575.11
1,269400419000,2252322516,22677766144,33104523264,35307520,0,668155,118259712,124645376,124645376,...,67.275,69.589,164662.007821,0.295,11.2,164662.007821,1.578,0.990,-6.305,5841.40
2,404545819000,1758135896,22674919424,33104523264,36950016,0,1105840,67637248,72368128,72368128,...,70.165,74.710,178185.008463,0.308,11.7,178185.008463,1.653,0.986,-7.613,3862.71
3,460082566000,115903139,22671982592,33104523264,38936576,0,1659803,47779840,50475008,50475008,...,97.096,88.251,217134.010313,0.423,6.2,217134.010313,1.590,0.997,-0.524,805.94
4,499557049000,1424465270,22669344768,33104523264,40976384,0,2098663,55451648,58753024,58753024,...,59.463,53.114,129720.006161,0.263,12.5,129720.006161,1.678,0.975,-7.156,3250.91

In [4]:
numerical_data.columns

Index(['cpu_usage_core_nanoseconds', 'cpu_usage_nanocores',
       'logsfs_available_bytes', 'logsfs_capacity_bytes', 'logsfs_used_bytes',
       'memory_major_page_faults', 'memory_page_faults', 'memory_rss_bytes',
       'memory_usage_bytes', 'memory_working_set_bytes',
       'rootfs_available_bytes', 'rootfs_capacity_bytes', 'rootfs_used_bytes',
       'kepler_container_joules_total',
       'kepler_container_microwatts_consumption_total', 'vm_id', 'cpuload',
       'disk_free', 'disk_total', 'disk_used', 'disk_used_percentage',
       'mem_free', 'mem_total', 'mem_used', 'mem_used_percentage', 'swap_free',
       'swap_total', 'swap_used', 'swap_used_percentage', 'uptime',
       'activePower', 'apparentPower', 'cumulatedEnergy', 'current',
       'currentTHD', 'partialEnergy', 'peakFactor', 'powerFactor',
       'reactivePower', 'latency_ms'],
      dtype='object')

In [6]:
numerical_data.drop(columns=['vm_id'], inplace=True)

/tmp/ipykernel_21264/971601798.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numerical_data.drop(columns=['vm_id'], inplace=True)

In [7]:
len(numerical_data.columns)

39

In [8]:
numerical_data.columns

Index(['cpu_usage_core_nanoseconds', 'cpu_usage_nanocores',
       'logsfs_available_bytes', 'logsfs_capacity_bytes', 'logsfs_used_bytes',
       'memory_major_page_faults', 'memory_page_faults', 'memory_rss_bytes',
       'memory_usage_bytes', 'memory_working_set_bytes',
       'rootfs_available_bytes', 'rootfs_capacity_bytes', 'rootfs_used_bytes',
       'kepler_container_joules_total',
       'kepler_container_microwatts_consumption_total', 'cpuload', 'disk_free',
       'disk_total', 'disk_used', 'disk_used_percentage', 'mem_free',
       'mem_total', 'mem_used', 'mem_used_percentage', 'swap_free',
       'swap_total', 'swap_used', 'swap_used_percentage', 'uptime',
       'activePower', 'apparentPower', 'cumulatedEnergy', 'current',
       'currentTHD', 'partialEnergy', 'peakFactor', 'powerFactor',
       'reactivePower', 'latency_ms'],
      dtype='object')